#!/bin/bash

DIBS_ROOT="$(dirname "$(readlink -f "${0}")")"
export DIBS_ROOT

if [[ $(id -u) -ne 0 ]] ; then
	echo "This script should be ran as root. Try sudo or su."
	exit
fi

exec bash --init-file ${DIBS_ROOT}/dibs/activate
