#!/bin/sh
### BEGIN INIT INFO
# Provides:          bluetooth-init
# Required-Start:    mountkernfs $local_fs urandom
# Required-Stop:     $local_fs
# X-Start-Before:    bluetooth
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Bluetooth initialization.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DEVICE=/dev/ttySAC1
MAC=aa:22:33:44:55:66
PID_FILE=/var/run/hciattach.pid

test -x /usr/local/bin/brcm_patchram_plus || exit 0
test -x /usr/bin/hciattach || exit 0
test -x /bin/hciconfig || exit 0

case "$1" in
    start)
        echo -n 1 > /sys/class/rfkill/rfkill0/state
        echo > $DEVICE
        /usr/local/bin/brcm_patchram_plus --patchram /lib/firmware/ap6210/bcm20702a.hcd --bd_addr $MAC --no2bytes --tosleep 5000 $DEVICE
        /usr/bin/hciattach -p $DEVICE any | tail -n 1 > $PID_FILE
        /bin/hciconfig hci0 up
    ;;
    stop)
        /bin/hciconfig hci0 down
        if [ -r $PID_FILE ]; then
            kill `cat $PID_FILE`
            rm $PID_FILE
        fi
        echo -n 0 > /sys/class/rfkill/rfkill0/state
    ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
    ;;
    *)
        N=/etc/init.d/bluetooth-init
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
    ;;
esac

exit 0
