#!/bin/bash

if [[ "$DIBS_ROOT" == "$PWD" ]] ; then
	echo "Cannot work in DIBS root, please create and change to a directory first"
	exit
fi

if [[ ! -h "kconfig" ]] ; then
	echo "DIBS environment not found. Try \"init\"."
fi

kconfig-mconf kconfig/Kconfig

