#!/bin/bash

case "$1" in
	build)
		;;

	config)
		;;

	help)
		echo "help: help [command ...]"
		echo "    Display information about DIBS commands."
		echo ""
		echo "    If command is not known, fallback to 'builtin help'"
		;;

	init)
		;;

	"")
		echo "DIBS commands:"
		echo " build"
		echo " config"
		echo " help"
		echo " init"
		;;

	*)
		builtin help "$@"
		;;
esac

