#!/bin/bash

if [[ "$DIBS_ROOT" == "$PWD" ]] ; then
	echo "Cannot work in DIBS root, create and change to a directory first"
	exit
fi

if [[ -n "$1" ]] ; then
	board="$1"
	if [[ ! -d "$DIBS_ROOT/boards/$board" ]] ; then
		echo "Board \"$board\" does not exist, aborting."
		return
	fi
	cp -r "$DIBS_ROOT/boards/$board/"* .
fi
ln -s "$DIBS_ROOT/kconfig"

