#!/bin/bash

if [[ "$DIBS_ROOT" == "$PWD" ]] ; then
	echo "Cannot work in DIBS root, please create and change to a directory first"
	exit
fi

source ${DIBS_ROOT}/tools/dibs/config-vars

workspace=$(readlink -f ${PWD})

if [[ "$1" == "clean" ]] ; then
	rm -r .fakeroot bootstrap configscript.sh multistrap.conf preseed
fi

f="preseed"
if [[ ! -f $f ]] ; then
	if [[ "$config_use_sysvinit" == "y" ]]; then
		echo "preseed/late_command=\"in-target apt-get install -y sysvinit-core\"" >> $f
	fi
fi

f="configscript.sh"
if [[ ! -f $f ]]; then
	echo "#!/bin/sh" >> $f
	echo "set -e" >> $f
	echo "export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true" >> $f
	echo "export LC_ALL=C LANGUAGE=C LANG=C" >> $f
	echo "/var/lib/dpkg/info/dash.preinst install" >> $f
	echo "if [ -d /tmp/preseeds/ ]; then" >> $f
	echo "	for file in `ls -1 /tmp/preseeds/*`; do" >> $f
	echo "	debconf-set-selections $file" >> $f
	echo "	done" >> $f
	echo "fi" >> $f
	echo "dpkg --configure -a" >> $f
	echo "mount proc -t proc /proc" >> $f
	echo "dpkg --configure -a" >> $f
	echo "umount /proc" >> $f
	chmod 755 $f
fi

f="multistrap.conf"
if [[ ! -f $f ]] ; then
	echo "[General]" >> $f
	echo "unpack=true" >> $f
	echo "debootstrap=${config_distro^}" >> $f
	echo "aptsources=${config_distro^}" >> $f
	echo "cleanup=true" >> $f
	echo "arch=${config_arch}" >> $f
	echo "directory=bootstrap" >> $f
	echo "retainsources=pkgcache" >> $f
	echo "debconfseed=preseed" >> $f
	echo "configscript=configscript.sh" >> $f
	echo >> $f

	if [[ "$config_distro" == "debian" ]] ; then
		echo "[Debian]" >> $f
		echo "source=http://deb.debian.org/debian" >> $f
		echo "keyring=debian-archive-keyring" >> $f
	elif [[ "$config_distro" == "ubuntu" ]] ; then
		echo "[Ubuntu]" >> $f
		echo "source=http://archive.ubuntu.com/ubuntu" >> $f
		echo "keyring=ubuntu-keyring" >> $f
	fi
	echo "suite=$config_release" >> $f
fi

if [[ "$config_distro" == "debian" ]] && [[ ! -f pkgcache/debian-archive-keyring_2017.6_all.deb ]] ; then
	fakeroot -i .fakeroot -s .fakeroot wget http://cdn-fastly.deb.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2017.6_all.deb -P pkgcache
elif [[ "$config_distro" == "ubuntu" ]] && [[ ! -f pkgcache/ubuntu-keyring_2016.10.27_all.deb ]] ; then
	fakeroot -i .fakeroot -s .fakeroot wget http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-keyring/ubuntu-keyring_2016.10.27_all.deb -P pkgcache
fi

if [[ -d pkgcache ]] ; then
	fakeroot -i .fakeroot -s .fakeroot mkdir -p bootstrap/var/cache/apt/archives
	fakeroot -i .fakeroot -s .fakeroot cp pkgcache/* bootstrap/var/cache/apt/archives
fi

fakeroot -i .fakeroot -s .fakeroot mkdir -p bootstrap pkgcache
fakeroot -i .fakeroot -s .fakeroot /usr/sbin/multistrap -f multistrap.conf
cd bootstrap
fakeroot -i ../.fakeroot -s ../.fakeroot tar -zcf ../bootstrap.tgz .
cd ..
fakeroot -i .fakeroot -s .fakeroot rm -r bootstrap

