#!/bin/bash

if [[ -z "$DIBS_ROOT" ]] ; then
	echo "DIBS_ROOT is not set."
	exit
fi

if [[ $(id -u) -ne 0 ]] ; then
	echo "This script should be ran as root."
	exit
fi

if [[ "$DIBS_ROOT" == "$PWD" ]] ; then
	echo "Cannot work in DIBS root. Please create a directory to use as a DIBS_WORKSPACE."
	exit
fi

KCONFIG_CONFIG="$DIBS_WORKSPACE/config/config"
export KCONFIG_CONFIG

function dibs_init()
{
	local board=${1:-generic}

	if [[ ! -d "$DIBS_ROOT/boards/$board" ]] ; then
		echo "Board \"$board\" does not exist, aborting."
		return
	fi

	echo "board=$board" > .dibs_workspace

	mkdir -p board
	shopt -s dotglob
	cp -r "$DIBS_ROOT/boards/$board/"* board
	shopt -u dotglob

	mkdir -p config
	ln -sf "$DIBS_ROOT/dibs" dibs
}

function require_workspace()
{
	if [[ "$DIBS_WORKSPACE" == "/" ]] || [[ ! -f "$DIBS_WORKSPACE/.dibs_workspace" ]]; then
		echo "DIBS workspace not found. Try creating a directory and run \"dibs init\"."
		exit
	fi
}

function require_config()
{
	if [[ ! -f "$DIBS_WORKSPACE/config/config" ]] ; then
		echo "Config not found. Try \"dibs config\"."
		exit
	fi
}

function require_rootfs_tar()
{
	if [[ ! -f $DIBS_WORKSPACE/rootfs.tar ]] ; then
		echo "rootfs.tar not found!  Have you ran \"dibs build\" yet?"
		exit
	fi
}

function require_rootfs_dir()
{
	if [[ ! -d $DIBS_WORKSPACE/rootfs ]] ; then
		echo "No extracted filesystem found. Did you run \"dibs untar\"?"
		exit
	fi
}

function dibs_config()
{
	require_workspace

	kconfig-mconf dibs/Kconfig
	if [[ -f config/config ]] ; then
		dibs_regen
	fi
}

function read_config()
{
	require_workspace
	require_config

	config_arch=""
	if [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s ARCH_AMD64)" ]] ; then
		config_arch="amd64"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s ARCH_ARM64)" ]] ; then
		config_arch="arm64"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s ARCH_ARMEL)" ]] ; then
		config_arch="armel"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s ARCH_ARMHF)" ]] ; then
		config_arch="armhf"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s ARCH_I386)" ]] ; then
		config_arch="i386"
	fi

	config_board=""
	if [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s BOARD_GENERIC)" ]] ; then
		config_board="generic"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s BOARD_NANOPI)" ]] ; then
		config_board="nanopi"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s BOARD_NANOPI2)" ]] ; then
		config_board="nanopi2"
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s BOARD_NANOPI_NEO_PLUS2)" ]] ; then
		config_board="nanopi_neo_plus2"
	fi

	config_distro=""
	config_release=""
	if [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s DISTRO_DEBIAN)" ]] ; then
		config_distro="debian"
		if [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_DEBIAN_WHEEZY)" ]]; then
			config_release="wheezy"
		elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_DEBIAN_JESSIE)" ]]; then
			config_release="jessie"
		elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_DEBIAN_STRETCH)" ]]; then
			config_release="stretch"
		elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_DEBIAN_TESTING)" ]]; then
			config_release="testing"
		fi
	elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s DISTRO_UBUNTU)" ]] ; then
		config_distro="ubuntu"
		if [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_UBUNTU_TRUSTY)" ]]; then
			config_release="trusty"
		elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_UBUNTU_XENIAL)" ]]; then
			config_release="xenial"
		elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_UBUNTU_ZESTY)" ]]; then
			config_release="zesty"
		elif [[ "y" == "$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s RELEASE_UBUNTU_ARTFUL)" ]]; then
			config_release="artful"
		fi
	fi

	config_use_sysvinit="$(kconfig-tweak --file "$DIBS_WORKSPACE/config/config" -s USE_SYSVINIT)"

	source "$DIBS_WORKSPACE/dibs/packages"
}

function dibs_regen()
{
	read_config

	local f="$DIBS_WORKSPACE/config/preseed"
	truncate -s 0 $f
	if [[ "$config_use_sysvinit" == "y" ]]; then
		echo "preseed/late_command=\"in-target apt-get install -y sysvinit-core\"" >> $f
	fi

	local f="$DIBS_WORKSPACE/config/stage2.sh"
	echo "#!/bin/sh" > $f
	echo >> $f
	echo "set -e" >> $f
	echo "export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true" >> $f
	echo "export LC_ALL=C LANGUAGE=C LANG=C" >> $f
	echo "/var/lib/dpkg/info/dash.preinst install" >> $f
	echo "if [ -d /tmp/preseeds/ ]; then" >> $f
	echo "	for file in \`ls -1 /tmp/preseeds/*\`; do" >> $f
	echo "	debconf-set-selections \$file" >> $f
	echo "	done" >> $f
	echo "fi" >> $f
	echo "dpkg --configure -a" >> $f
	echo "mount proc -t proc /proc" >> $f
	echo "dpkg --configure -a" >> $f
	echo "umount /proc" >> $f
	echo "rm /stage2.sh" >> $f
	echo "if [ -d /tmp/preseeds ]; then" >> $f
	echo "	rm -r /tmp/preseeds" >> $f
	echo "fi" >> $f
	chmod 755 $f

	local f="$DIBS_WORKSPACE/config/multistrap.conf"
	echo "[General]" > $f
	echo "noauth=true" >> $f
	echo "unpack=true" >> $f
	echo "debootstrap=${config_distro^}" >> $f
	echo "aptsources=${config_distro^}" >> $f
	echo "cleanup=true" >> $f
	echo "arch=${config_arch}" >> $f
	echo "directory=rootfs" >> $f
	echo "debconfseed=config/preseed" >> $f
	echo "configscript=config/stage2.sh" >> $f
	echo >> $f
	if [[ "$config_distro" == "debian" ]] ; then
		echo "[Debian]" >> $f
		echo "packages=$config_packages" >> $f
		echo "source=http://deb.debian.org/debian" >> $f
	elif [[ "$config_distro" == "ubuntu" ]] ; then
		echo "[Ubuntu]" >> $f
		if [[ "$config_arch" != "amd64" ]] && [[ "$config_arch" != "i386" ]] ; then
			echo "packages=$config_packages" >> $f
			echo "source=http://ports.ubuntu.com/ubuntu-ports" >> $f
		else
			echo "source=http://archive.ubuntu.com/ubuntu" >> $f
		fi
	fi
	echo "suite=$config_release" >> $f
}

# assumes read_config has already been ran
function install_static_qemu()
{
	if [[ "$PWD" == "/" ]] ; then
		echo "install_static_qemu function cowardly refusing to run."
		exit
	fi

	if [[ "$config_arch" == "armel" ]] || [[ "$config_arch" == "armhf" ]] ; then
		cp /usr/bin/qemu-arm-static usr/bin
	elif [[ "$config_arch" == "arm64" ]] ; then
		cp /usr/bin/qemu-aarch64-static usr/bin
	fi
}

# assumes read_config has already been ran
function uninstall_static_qemu()
{
	if [[ "$PWD" == "/" ]] ; then
		echo "uninstall_static_qemu function cowardly refusing to run."
		exit
	fi

	if [[ "$config_arch" == "armel" ]] || [[ "$config_arch" == "armhf" ]] ; then
		rm -f usr/bin/qemu-arm-static
	elif [[ "$config_arch" == "arm64" ]] ; then
		rm -f usr/bin/qemu-aarch64-static
	fi
}

function dibs_build()
{
	read_config

	mkdir -p rootfs
	multistrap -f config/multistrap.conf
	cd rootfs
	install_static_qemu
	chroot . /bin/bash /stage2.sh
	source "$DIBS_WORKSPACE/dibs/network"
	uninstall_static_qemu
	dibs_tar
}	

function unmount_rootfs_subdirs()
{
	IFS=$'\n'
	for line in $(mount) ; do
		local mountpoint="$(echo $line | cut -d' ' -f3)"
		if [ "${mountpoint##$DIBS_WORKSPACE/rootfs/}" != "${mountpoint}" ] ; then
			umount -R "$mountpoint"
		fi
	done
	IFS=' '
}

function dibs_untar()
{
	require_rootfs_tar

	mkdir -p "$DIBS_WORKSPACE/rootfs"
	cd "$DIBS_WORKSPACE/rootfs"
	tar -xf "$DIBS_WORKSPACE/rootfs.tar"
}

function dibs_tar()
{
	require_rootfs_dir
	unmount_rootfs_subdirs

	cd "$DIBS_WORKSPACE/rootfs"
	tar -cf --one-file-system "$DIBS_WORKSPACE/rootfs.tar" .
	cd "$DIBS_WORKSPACE"
	rm -rf --one-file-system "$DIBS_WORKSPACE/rootfs"
}

function dibs_shell()
{
	read_config

	dibs_untar
	install_static_qemu
	mount -t devtmpfs devtmpfs "$DIBS_WORKSPACE/rootfs/dev"
	mount -t tmpfs tmpfs "$DIBS_WORKSPACE/rootfs/tmp"
	mount -t proc proc "$DIBS_WORKSPACE/rootfs/proc"
	chroot "$DIBS_WORKSPACE/rootfs" /bin/bash
	uninstall_static_qemu
	dibs_tar
}

function dibs_help()
{
	command=$1
	case "$1" in
		init)
			echo "init: dibs init [board]"
			echo "    Initializes a workspace, optionally with a given board preset."
			;;
		config)
			echo "config: dibs config [board]"
			echo "    Pre-build configuration. First runs kconfig-mconfig and then"
			echo "    generates output files."
			;;
		regen)
			echo "regen: dibs regen"
			echo "    Rebuilds all configuration dependent files such as multistrap.conf."
			;;
		build)
			echo "build: dibs build"
			echo "    Runs multistrap and stage2 chroot processes."
			;;
		shell)
			echo "shell: dibs shell"
			echo "    Starts a chroot shell in the rootfs."
			;;
		tar)
			echo "tar: dibs tar"
			echo "    Makes a rootfs.tar from the contents of a rootfs directory."
			;;
		untar)
			echo "untar: dibs untar"
			echo "    Extracts a rootfs.tar file into a rootfs directory."
			;;
		*)
			echo "Usage:"
			echo " build"
			echo " config [board]"
			echo " init"
			echo " regen"
			echo " shell"
			echo " tar"
			echo " untar"
			;;
	esac
}

command=$1
shift

case "$command" in
	init)
		dibs_init "$@"
		;;
	config)
		dibs_config "$@"
		;;
	regen)
		dibs_regen "$@"
		;;
	build)
		dibs_build "$@"
		;;
	shell)
		dibs_shell "$@"
		;;
	untar)
		dibs_untar "$@"
		;;
	tar)
		dibs_tar "$@"
		;;
	help|"")
		dibs_help "$@"
		;;
	*)
		echo "Unknown command, see \"dibs help\"."
		;;
esac

